version: '3.5'
services:
  nexus:
    image: "sonatype/nexus3"
    deploy:
      replicas: 1
      placement:
       constraints:
         - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nexus.rule=Host(`nexus.pfeelyes.space`)"
        - "traefik.http.services.nexus.loadbalancer.server.port=8081"
        - "traefik.http.routers.nexus.entrypoints=websecure"
        - "traefik.http.routers.nexus.tls=true"
        - "traefik.http.routers.nexus.tls.certresolver=myresolver"
#    ports:
#      - 83:8081
#      - 18779:18779
    networks:
      - proxy
    volumes:
      - nexus_data:/nexus-data
    restart: always

volumes:
  nexus_data:
    external: true
networks:
  proxy:
    external: true